pipeline {
  agent any

  environment {
    BACKEND_IMAGE = 'aryanraj2400/code-review-backend:latest'
    FRONTEND_IMAGE = 'aryanraj2400/code-review-frontend:latest'
  }

  stages {
    stage('Clone Code') {
      steps {
        git 'https://github.com/Aryanraj2400/Ai-Code-Reviewer.git'
      }
    }

    stage('Build Docker Images') {
      steps {
        sh 'docker build -t $BACKEND_IMAGE ./Backend'
        sh 'docker build -t $FRONTEND_IMAGE ./Frontend'
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
          sh 'docker push $BACKEND_IMAGE'
          sh 'docker push $FRONTEND_IMAGE'
        }
      }
    }

    // stage('Deploy to Kubernetes') {
    //   steps {
    //     sh 'kubectl apply -f k8s/backend-deployment.yaml'
    //     sh 'kubectl apply -f k8s/frontend-deployment.yaml'
    //     sh 'kubectl apply -f k8s/service.yaml'
    //   }
    // }
  }
}
